language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
    
jdk:
  - oraclejdk8
  - openjdk7

env:
  - BUILD_ANDROID=false
  - BUILD_ANDROID=true

matrix:
  exclude:
    - jdk: openjdk7
      env: BUILD_ANDROID=true

cache:
  directories:
    - $HOME/.gradle/caches/4.4.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_script:
  - if [ "$BUILD_ANDROID" = "true" ]; then echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a; fi
  - if [ "$BUILD_ANDROID" = "true" ]; then emulator -avd test -no-skin -no-audio -no-window & fi
  - if [ "$BUILD_ANDROID" = "true" ]; then android-wait-for-emulator; fi
  - if [ "$BUILD_ANDROID" = "true" ]; then adb shell input keyevent 82 & fi

script: if [ "$BUILD_ANDROID" = "true" ]; then ./gradlew connectedAndroidTest; else ret=0; ./gradlew java:testRealtimeSuite || ret=1; ./gradlew java:testRestSuite || ret=1; exit $ret; fi

# Buffer overflow patch. Source: https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165135711
before_install:
  - if [ "$BUILD_ANDROID" = "false" ]; then cat /etc/hosts; fi
  - if [ "$BUILD_ANDROID" = "false" ]; then sudo hostname "$(hostname | cut -c1-63)"; fi
  - if [ "$BUILD_ANDROID" = "false" ]; then sudo sed -i -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts; fi
  - if [ "$BUILD_ANDROID" = "false" ]; then cat /etc/hosts; fi

install: true
