# This is a manually triggered workflow (hence on: workflow_dispatch).
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

name: Publish to Maven Central
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version, without v prefix, appended to v to locate tag'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.version }}

      # Gradle 7 requires Java 11 to run
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Publish to Repositories
        env:
          ORG_GRADLE_PROJECT_OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_RING_FILE_BASE64 }}
        run: |
          echo "Publishing version ${{ github.event.inputs.version }} to MavenCentral..."
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
